# Generated by Django 3.0.2 on 2020-03-30 19:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=196, unique=True)),
                ('last_deployment', models.IntegerField(default=0)),
                ('current_deployment_var', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('last_deployed_var', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Global_Config',
            fields=[
                ('name', models.CharField(max_length=196, primary_key=True, serialize=False)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'verbose_name_plural': 'Global Configurations',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=196)),
                ('template', models.TextField()),
                ('required', django.contrib.postgres.fields.jsonb.JSONField(default=manager.models.defaultTemplate)),
            ],
        ),
    ]
