# Generated by Django 3.0.2 on 2020-04-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='required',
            new_name='schema',
        ),
    ]
